[package]
name = "closed_svg_path"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics-core = "0.4.0"
embedded-graphics = "0.8.1"
num-traits ={ version= "0.2.19", default-features = false, features = ["libm"]  }
num_enum = { version = "0.7", default-features = false }