[package]
name = "closed_svg_path_proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
svgtypes = "0.15.3"
roxmltree = "0.20.0"
quote = "1.0"
syn = "2.0"
proc-macro2 = {version="1.0", features = ["span-locations"] }
closed_svg_path = {path="../closed_svg_path"}